
ALTER TABLE "TODO_USERS" ADD COLUMN IF NOT EXISTS "is_admin" BOOLEAN DEFAULT FALSE;

ALTER TABLE "todo_tasks" ADD COLUMN IF NOT EXISTS "is_agent_task" BOOLEAN DEFAULT FALSE;
ALTER TABLE "todo_tasks" ADD COLUMN IF NOT EXISTS "agent_url" TEXT;
ALTER TABLE "todo_tasks" ADD COLUMN IF NOT EXISTS "open_in_new_window" BOOLEAN DEFAULT FALSE;
